version: "3.7"
services:
  bot:
    image: ghcr.io/modmail-dev/modmail@sha256:b014674c9f141a73e584b546a2ae19eb384732b1fb786639820faea2b455a7fa
    restart: always
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
  logviewer:
    image: ghcr.io/modmail-dev/logviewer:master
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
    ports:
      - 80:8000
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
